config/routes.rb
Longislandjoblink::Application.routes.draw do
  
  resources :friendships do 
    resources :friendshipcomments
  end 
  

  devise_for :users

  resources :loops do 
    resources :comments 
  end

  get "home/index"
    
  resources :locations, :only => [ :index] do 
    resources :jobs, :only => [ :index, :show, :new, :create]
  end

  resources :newsletters
  resources :users

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :loops, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships, :dependent => :destroy
  has_many :comments
  has_many :friendshipcomments
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :token, :comment
  # attr_accessible :title, :body
  
  before_create :generate_token

   protected

   def generate_token
     begin
       token = SecureRandom.hex(3)
     end while User.where(:token => token).exists?
     self.token = token
   end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @user = current_user
     @loops = @user.loops
     @search = User.search(params[:q])
     @users = @search.result(:distinct => true)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_adduserdashbar.html.erb
<div class="row-fluid">
	<div class="span12">
		<div id="second-bar">	
			
			<div class="span9">

				<div id="loop-dashboard-addcontact">
				<%= link_to new_loop_path, :class => "add-contact-to-loop" do %>
				<div class="btn"> <i class="icon-plus"></i> Add contact</div>
				<% end %>
				</div>
			</div>	
			
			<div class="span3">
				<% if user_signed_in? %>
				<div id="user-login">
				 	<%= link_to destroy_user_session_path, method: :delete, :class => "logout-link"  do  %>
					<div class="btn">
					<%= "Logout" %>
					</div>
				</div>	
				<% end %>
				<% end %>
			</div>
			
					
		</div>	
	</div>
</div>

app/views/users/index.html.erb
<%= render 'adduserdashbar' %>

<% if @search.conditions.empty? == false %>
		
<% @users.each do |user| %>

	<div class="container">
	<div class="show-wrapper">	
				<div class="row-fluid">
					<div class="span9">
						<div class="title">
							<%= user.firstname %> <%= user.lastname %> 
							</div>
						<div class="how-we-met-wrapper">
					 		<div id="how-we-met-location"> 
									<div class="span12">
									<div class="add-contact-wrapper">
									You have found <%= user.firstname%>! Looks like <%= user.firstname %> has shared his loop number with you so that you can store his networking profile. 
									<div class="add-contact-button-wrapper">
										<div class="row-fluid">
										<div class="span6">
											<%= link_to friendships_path(:friend_id => user), :class => "btn btn-large", :method => :post do  %>
											<%= "Add to dashboard"  %>
											<% end %>
										</div>
										<div class="span6">
												<%= link_to loops_path, :class => "btn btn-large" do %>
												<%= "Cancel" %>
												<% end %>
										</div>
										</div>	
									</div>	
											
									</div>			
									</div>
								</div>
						</div>
					</div>
					
					
				
				
				<div class="span3">
					<div id="contact-heading">
						Contact info
					</div>

					<div class="row-fluid">
						<div class="span12">
							<div id="contact-field-css">
								Title
								</div>
							<div id="contact-answer-css">
							<%= user.title %>
							</div>
							<br>
							<div id="contact-field-css">
								Industry
								</div>
							<div id="contact-answer-css">
							<%= user.industry %>
							</div>
							<br>
							<div id="contact-field-css">
								Phone
								</div>
							<div id="contact-answer-css">
							<%= user.phone %>
							</div>
							<br>
							<div id="contact-field-css">
							Email
							</div>
							<div id="contact-answer-css">
							<%= mail_to "#{user.email}" %>
							</div>
							<br>
							<div id="contact-field-css">
								Website:
								</div>
							<div id="contact-answer-css"><%= link_to "#{user.website}", user.website %></div>
						</div>
					</div>
		  		</div>
			</div>	

<% end %>
<% else %>
Sorry, looks like that loop # didn't work. Please try again and remember, they are case-sensitive! <%= link_to "Back", 	 'loops/new' %>
<% end %>
			

app/views/users/search_loop.html.erb
	<div class="span12">
		<div id="find-token-heading">
			Add a contact instantly if you know the loop number:
			</div>


<%= search_form_for @search do |f| %>
<%= f.text_field :token_eq, :class => "find-token-field" %>
<% end %>
<br>

	</div>
</div>