config/routes.rb
Longislandjoblink::Application.routes.draw do
  
  resources :friendships do 
    resources :friendshipcomments
  end 
  

  devise_for :users

  resources :loops do 
    resources :comments 
  end

  get "home/index"
    
  resources :locations, :only => [ :index] do 
    resources :jobs, :only => [ :index, :show, :new, :create]
  end

  resources :newsletters
  resources :users

  root :to => 'home#index'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_many :friendshipcomments
  
  attr_accessible :friend_id, :user_id
  
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to loops_path, notice: 'Added successfully' }
        format.json { render json: @friendship, status: :created, location: @friendship }
      else
        format.html { render loops_path, notice: 'You have already added this user' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to loops_path, notice: 'This person has been removed' }
      format.json { head :no_content }
    end
  end
  
  
  # GET /loops/1
  # GET /loops/1.json
  def show
    @friendship = current_user.friendships.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @loop }
    end
  end
  
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/_friendshipdashbarshow.html.erb
<div class="row-fluid">
	<div class="span12">
		<div id="second-bar">
				<div class="span9">
					
					
					<div id="loop-dashboard-back">
					<%= link_to loops_path, :class => "btn" do %>
					<%= "Back to Dashboard" %>
					<% end %>
					</div>
				
					
					<div id="loop-dashboard-addcontact">
					<%= link_to new_loop_path, :class => "add-contact-to-loop" do %>
					<div class="btn"> <i class="icon-plus"></i> Add contact</div>
					<% end %>
					</div>
					
						
						
							<div id="loop-dashboard-deletecontact">
							<%= link_to friendship_path(@friendship), :method => :delete, :confirm => "Are you sure?", :class => "btn" do %>
							<%= 'Delete contact' %>
							<% end %>
							</div>
						
					
				</div>	
			
			<div class="span3">
				<% if user_signed_in? %>
				<div id="user-login">
				 	<%= link_to destroy_user_session_path, method: :delete, :class => "logout-link"  do  %>
					<div class="btn">
					<%= "Logout" %>
					</div>
				</div>	
				<% end %>
				<% end %>
			</div>
			
					
		</div>	
	</div>
</div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendships.each do |friendship| %>
  <tr>
    <td><%= link_to 'Show', friendship %></td>
    <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
    <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<%= render 'friendshipdashbarshow' %>


	<div class="container">
	<div class="show-wrapper">	
				<div class="row-fluid">
					<div class="span9">
						<div class="title">
							<%= @friendship.friend.firstname %> <%= @friendship.friend.lastname %> <div id="met-date"> | <%= @friendship.created_at.strftime('%b %d, %Y') %> </div>
							</div>
						<div class="how-we-met-wrapper">
					 		
						</div>
					</div>
				
				
				<div class="span3">
					<div id="contact-heading">
						Contact info
					</div>

					<div class="row-fluid">
						<div class="span12">
							<div id="contact-field-css">
								Title
								</div>
							<div id="contact-answer-css">
							<%= @friendship.friend.title %>
							</div>
							<br>
							<div id="contact-field-css">
								Industry
								</div>
							<div id="contact-answer-css">
							<%= @friendship.friend.industry %>
							</div>
							<br>
							<div id="contact-field-css">
								Phone
								</div>
							<div id="contact-answer-css">
							<%= @friendship.friend.phone %>
							</div>
							<br>
							<div id="contact-field-css">
							Email
							</div>
							<div id="contact-answer-css">
							<%= mail_to "#{@friendship.friend.email}" %>
							</div>
							<br>
							<div id="contact-field-css">
								Website:
								</div>
							<div id="contact-answer-css"><%= link_to "#{@friendship.friend.website}", @friendship.friend.website %></div>
						</div>
					</div>
		  		</div>
			</div>	


		
						<div class="row-fluid">

							<div class="span12">
								<div class="span12">

									<div class="heading-notes">
										Notes
										</div>

											<div id="comment-section">

												<div id="comment-section-heading">	

													<% @friendship.friendshipcomments.reverse.each do |comment| %>
													<div id="comment-section-body">
													<%= comment.body %>
													<div id="comment-section-created_at">
														<%= comment.created_at.strftime('%l:%M %p %b %d, %Y ')%>

													</div>	
													</div>

												<% end %>

												</div>
											</div>	
										</div>


										<%= form_for ([@friendship, @friendship.friendshipcomments.build]), :class => "loop-show-comment-form" do |f| %>

							  			<div class="field">
										<%= f.text_area :body, :class => "loop-show-comment-form", :placeholder => "New note about #{@friendship.friend.firstname}", :rows => 5, :style => "width:100%;" %></br>
										</div>

										<%= f.submit 'Add note', :class => "btn" %>
										<% end %>

							</div>		



						</div>

			</div>
		
	</div>		
</div>