config/routes.rb
Longislandjoblink::Application.routes.draw do
  
  resources :friendships do 
    resources :friendshipcomments
  end 
  

  devise_for :users

  resources :loops do 
    resources :comments 
  end

  get "home/index"
    
  resources :locations, :only => [ :index] do 
    resources :jobs, :only => [ :index, :show, :new, :create]
  end

  resources :newsletters
  resources :users

  root :to => 'home#index'

end

app/models/friendshipcomment.rb
class Friendshipcomment < ActiveRecord::Base
    belongs_to :friendship
    belongs_to :user
    attr_accessible :body, :user_id, :friendship_id
end

app/controllers/friendshipcomments_controller.rb
class FriendshipcommentsController < ApplicationController
  def create
      @friendship = Friendship.find(params[:friendship_id])
      @friendshipcomment = @friendship.friendshipcomments.build(params[:friendshipcomment])
      @friendshipcomment.user_id = current_user.id
      @friendshipcomment.save!
      redirect_to friendship_path(@friendship)
  end
end

app/helpers/friendshipcomments_helper.rb
module FriendshipcommentsHelper
end

app/views/friendshipcomments/_form.html.erb
<%= form_for(@friendshipcomment) do |f| %>
  <% if @friendshipcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendshipcomment.errors.count, "error") %> prohibited this friendshipcomment from being saved:</h2>

      <ul>
      <% @friendshipcomment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendshipcomments/edit.html.erb
<h1>Editing friendshipcomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendshipcomment %> |
<%= link_to 'Back', friendshipcomments_path %>

app/views/friendshipcomments/index.html.erb
<h1>Listing friendshipcomments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friendshipcomments.each do |friendshipcomment| %>
  <tr>
    <td><%= link_to 'Show', friendshipcomment %></td>
    <td><%= link_to 'Edit', edit_friendshipcomment_path(friendshipcomment) %></td>
    <td><%= link_to 'Destroy', friendshipcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friendshipcomment', new_friendshipcomment_path %>

app/views/friendshipcomments/new.html.erb
<h1>New friendshipcomment</h1>

<%= render 'form' %>

<%= link_to 'Back', friendshipcomments_path %>

app/views/friendshipcomments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friendshipcomment_path(@friendshipcomment) %> |
<%= link_to 'Back', friendshipcomments_path %>